// app/components/DisplayUsers.jsx
import React from 'react';
import { Container } from 'flux/utils';

import AppStore from '../stores/AppStore';
import UserDisplay from './UserDisplay';

class _DisplayUsers extends React.Component {
  static getStores() {
    return [AppStore];
  }

  static calculateState() {
    return {
      users: AppStore.getState()
    };
  }

  render() {
    let users = this.state.users.map(user => { 
      return (
        <UserDisplay
          fName={ user.firstName }
          lName={ user.lastName }
          addr={ user.address }
          id={ user.id }
          key={ user.id }
        />
      );
    });

    return (
      <div>
        {users.length ? users : 'Please add Users for display'}
      </div>
    );
  }
}

const DisplayUsers = Container.create(_DisplayUsers);
export default DisplayUsers;

// Vue/client/components/DisplayUsers.vue
<template>
  <div class="user-wrapper">
    <div v-if="!users.length">
      <p> Please add users for display </p>
    </div>
    <div v-else v-for="user in users">
      <user-display :user="user" :key="user.id"></user-display>
    </div>
  </div>
</template>

<script>
import UserDisplay from '@cmp/UserDisplay'

export default {
  name: 'display-users',
  computed: {
    users () { return this.$store.state.users }
  },
  components: {
    UserDisplay
  }
}
</script>

<style scoped>
.user-wrapper {
 display:flex;
 flex-wrap: wrap;
}
